### ISSUE TITLE
npm i @openkraken/cli -g 报错

### ISSUE THREAD

**Issue by valleylmh** [openkraken/kraken#105]
Error: Command failed: tar xzf C:\Users\liumh29487\AppData\Roaming\npm\node_modules\@openkraken\cli\kraken-win32-0.7.0.tar.gz -C ./build
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at Object.<anonymous> (C:\Users\liumh29487\AppData\Roaming\npm\node_modules\@openkraken\cli\install.js:15:1)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18076,
  stdout: null,
  stderr: null
}

**Comment by wssgcg1213** [comment]
@andycall 看起来是路径缺少一个 `\`

**Comment by wssgcg1213** [comment]
https://github.com/openkraken/cli/blob/master/install.js#L15

**Comment by andycall** [comment]
Cli 目前不支持 Windows

**Comment by wssgcg1213** [comment]
@valleylmh windows 下的 bin 暂时还不支持, 建议在 Android/iOS/macOS 下体验
