### ISSUE TITLE
编译总是失败

### ISSUE THREAD

**Issue by yoyo89757001** [openkraken/kraken#1104]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

最新

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 2,
  name: 'build-android-kraken-lib',
  branch: false,
  error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/chenjun/Library/Android/sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake     -DANDROID_NDK=/Users/chenjun/Library/Android/sdk/ndk/21.4.7075529     -DIS_ANDROID=TRUE     -DANDROID_ABI="arm64-v8a"     \
           -DANDROID_PLATFORM="android-18"     -DANDROID_STL=c++_shared     -G "Unix Makefiles"     -B /Users/chenjun/krakenSDK/kraken/bridge/cmake-build-android-arm64-v8a -S /Users/chenjun/krakenSDK/kraken/bridge
      at checkExecSyncError (node:child_process:826:11)
      at execSync (node:child_process:900:15)
      at /Users/chenjun/krakenSDK/kraken/scripts/tasks.js:661:5
      at Array.forEach (<anonymous>)
      at /Users/chenjun/krakenSDK/kraken/scripts/tasks.js:657:9
      at taskWrapper (/Users/chenjun/krakenSDK/kraken/node_modules/undertaker/lib/set-task.js:13:15)
      at bound (node:domain:421:15)
      at runBound (node:domain:432:12)
      at asyncRunner (/Users/chenjun/krakenSDK/kraken/node_modules/async-done/index.js:55:18)
      at processTicksAndRejections (node:internal/process/task_queues:78:11) {
    status: 127,
    signal: null,
    output: [ null, null, null ],
    pid: 12245,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 0, 14079750 ],
  time: 1642385834539
})
    at new NodeError (node:internal/errors:371:5)
    at Gulp.emit (node:events:379:17)
    at Gulp.emit (node:domain:475:12)
    at Object.error (/Users/chenjun/krakenSDK/kraken/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/chenjun/krakenSDK/kraken/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/chenjun/krakenSDK/kraken/node_modules/once/once.js:25:25)
    at f (/Users/chenjun/krakenSDK/kraken/node_modules/once/once.js:25:25)
    at tryCatch (/Users/chenjun/krakenSDK/kraken/node_modules/async-done/index.js:24:15)
    at done (/Users/chenjun/krakenSDK/kraken/node_modules/async-done/index.js:40:12)
    at Domain.onError (/Users/chenjun/krakenSDK/kraken/node_modules/async-done/index.js:51:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 2,
    name: 'build-android-kraken-lib',
    branch: false,
    error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/chenjun/Library/Android/sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake     -DANDROID_NDK=/Users/chenjun/Library/Android/sdk/ndk/21.4.7075529     -DIS_ANDROID=TRUE     -DANDROID_ABI="arm64-v8a"     \
             -DANDROID_PLATFORM="android-18"     -DANDROID_STL=c++_shared     -G "Unix Makefiles"     -B /Users/chenjun/krakenSDK/kraken/bridge/cmake-build-android-arm64-v8a -S /Users/chenjun/krakenSDK/kraken/bridge
        at checkExecSyncError (node:child_process:826:11)
        at execSync (node:child_process:900:15)
        at /Users/chenjun/krakenSDK/kraken/scripts/tasks.js:661:5
        at Array.forEach (<anonymous>)
        at /Users/chenjun/krakenSDK/kraken/scripts/tasks.js:657:9
        at taskWrapper (/Users/chenjun/krakenSDK/kraken/node_modules/undertaker/lib/set-task.js:13:15)
        at bound (node:domain:421:15)
        at runBound (node:domain:432:12)
        at asyncRunner (/Users/chenjun/krakenSDK/kraken/node_modules/async-done/index.js:55:18)
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      status: 127,
      signal: null,
      output: [ null, null, null ],
      pid: 12245,
      stdout: null,
      stderr: null,
      domainThrown: true
    },
    duration: [ 0, 14079750 ],
    time: 1642385834539
  }
}

android SDK 路径没有问题。设备是 mac M1 芯片。

**Comment by yoyo89757001** [comment]
NDK 也没问题。![image](https://user-images.githubusercontent.com/31086765/149692844-938ade02-917c-4308-84a0-d0a64d9b9c4e.png)

**Comment by andycall** [comment]
只给了错，没有给出原因

**Comment by wssgcg1213** [comment]
cmake 命令有吗

**Comment by yoyo89757001** [comment]
![image](https://user-images.githubusercontent.com/31086765/149722352-db690760-b801-4d78-87a1-10d7ded1e0e7.png)

**Comment by yoyo89757001** [comment]
有make. 没有cmake哦

**Comment by andycall** [comment]
Prerequisites

Node.js v12.0 or later
Flutter version in the kraken/pubspec.yaml
CMake v3.2.0 or later
Xcode (10.12) or later (Running on macOS or iOS)
Android NDK version 21.4.7075529 (Running on Android)

**Comment by yoyo89757001** [comment]
安装后可以了

**Comment by yoyo89757001** [comment]
启动为什么白屏呢
![image](https://user-images.githubusercontent.com/31086765/149856465-128c7770-614f-410c-9fc0-c6e71f692e3f.png)

**Comment by andycall** [comment]
地址被墙了

**Comment by yoyo89757001** [comment]
不对哦，可以打开 ![image](https://user-images.githubusercontent.com/31086765/149866520-bcdc2add-509a-48c8-a1a5-6823eb10e5d5.png)

**Comment by yoyo89757001** [comment]
![image](https://user-images.githubusercontent.com/31086765/149866822-a265b101-4246-4e76-8a55-763612d4d9c8.png)
