### ISSUE TITLE
windos 编译失败

### ISSUE THREAD

**Issue by yoyo89757001** [openkraken/kraken#1120]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

最新clone 

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by yoyo89757001** [comment]
![image](https://user-images.githubusercontent.com/31086765/150110245-871009b6-5276-467f-8614-fe0521061279.png)

**Comment by yoyo89757001** [comment]
cmake version 3.18.1-g262b901-dirty
NDK 21.4.7075529

不知道出现图片上错误是什么原因

**Comment by yoyo89757001** [comment]
![image](https://user-images.githubusercontent.com/31086765/150112163-6cdebfc3-42ac-430b-9823-59cec500cc8c.png)
![image](https://user-images.githubusercontent.com/31086765/150112438-97301c51-8c77-4247-a958-141f26ad841e.png)

**Comment by yoyo89757001** [comment]
![image](https://user-images.githubusercontent.com/31086765/150115224-cc8b29d1-eeef-477c-89da-ed8b3ec32812.png)
在这里把 git的路径改成自己的之后，又出现新的问题

**Comment by yoyo89757001** [comment]
> node scripts/build_android_so

usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone             Clone a repository into a new directory
   init              Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add               Add file contents to the index
   mv                Move or rename a file, a directory, or a symlink
   restore           Restore working tree files
   rm                Remove files from the working tree and from the index
   sparse-checkout   Initialize and modify the sparse-checkout

examine the history and state (see also: git help revisions)
   bisect            Use binary search to find the commit that introduced a bug
   diff              Show changes between commits, commit and working tree, etc
   grep              Print lines matching a pattern
   log               Show commit logs
   show              Show various types of objects
   status            Show the working tree status

grow, mark and tweak your common history
   branch            List, create, or delete branches
   commit            Record changes to the repository
   merge             Join two or more development histories together
   rebase            Reapply commits on top of another base tip
   reset             Reset current HEAD to the specified state
   switch            Switch branches
   tag               Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch             Download objects and refs from another repository
   pull              Fetch from and integrate with another repository or a local branch
   push              Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.
D:\kraken\node_modules\async-done\index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 0,
  name: 'android-so-clean',
  branch: false,
  error: Error: Command failed: rm -rf D:\kraken\bridge/build/android
      at checkExecSyncError (child_process.js:790:11)
      at execSync (child_process.js:863:15)
      at D:\kraken\scripts\tasks.js:757:3
      at android-so-clean (D:\kraken\node_modules\undertaker\lib\set-task.js:13:15)
      at bound (domain.js:421:15)
      at runBound (domain.js:432:12)
      at asyncRunner (D:\kraken\node_modules\async-done\index.js:55:18)
      at processTicksAndRejections (internal/process/task_queues.js:77:11) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 8264,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 0, 49229600 ],
  time: 1642588595842
})
    at new NodeError (internal/errors.js:322:7)
    at Gulp.emit (events.js:389:17)
    at Gulp.emit (domain.js:475:12)
    at Object.error (D:\kraken\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (D:\kraken\node_modules\now-and-later\lib\mapSeries.js:47:14)
    at f (D:\kraken\node_modules\once\once.js:25:25)
    at f (D:\kraken\node_modules\once\once.js:25:25)
    at tryCatch (D:\kraken\node_modules\async-done\index.js:24:15)
    at done (D:\kraken\node_modules\async-done\index.js:40:12)
    at Domain.onError (D:\kraken\node_modules\async-done\index.js:51:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 0,
    name: 'android-so-clean',
    branch: false,
    error: Error: Command failed: rm -rf D:\kraken\bridge/build/android
        at checkExecSyncError (child_process.js:790:11)
        at execSync (child_process.js:863:15)
        at D:\kraken\scripts\tasks.js:757:3
        at android-so-clean (D:\kraken\node_modules\undertaker\lib\set-task.js:13:15)
        at bound (domain.js:421:15)
        at runBound (domain.js:432:12)
        at asyncRunner (D:\kraken\node_modules\async-done\index.js:55:18)
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      status: 1,
      signal: null,
      output: [ null, null, null ],
      pid: 8264,
      stdout: null,
      stderr: null,
      domainThrown: true
    },
    duration: [ 0, 49229600 ],
    time: 1642588595842
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:bridge:android: `node scripts/build_android_so`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:bridge:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2022-01-19T10_36_35_874Z-debug.log

**Comment by wssgcg1213** [comment]
related to https://github.com/openkraken/kraken/pull/917
