### ISSUE TITLE
M1电脑build bridge时候报错

### ISSUE THREAD

**Issue by WK726** [openkraken/kraken#1197]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

main分支中的最新代码

### 重现步骤 ｜ Steps To Reproduce

电脑是刚换的m1电脑
在kraken中build bridge，以下是命令和报错信息

wangk@EBJ1203496 kraken % npm run build:bridge:ios:release

> build:bridge:ios:release
> KRAKEN_BUILD=Release node scripts/build_ios_framework

> build:release
> NODE_ENV=production rollup --config rollup.config.js && npm run mainToC && npm run testToC

src/index.ts → dist/main.js...
Created bundle main.js: 28.81 kB → 9.45 kB (gzip)
created dist/main.js in 1.2s

src/test/index.js → dist/test.js...
Created bundle test.js: 255.04 kB → 51.27 kB (gzip)
created dist/test.js in 262ms

> mainToC
> node scripts/js_to_c.js -s ../dist/main.js -o ../dist

/Users/wangk/Desktop/elongHotel/kraken/bridge/polyfill/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/Users/wangk/Desktop/elongHotel/kraken/bridge/polyfill/node_modules/qjsc/build/Release/qjsc_20210327.node, 0x0001): tried: '/Users/wangk/Desktop/elongHotel/kraken/bridge/polyfill/node_modules/qjsc/build/Release/qjsc_20210327.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/qjsc_20210327.node' (no such file), '/usr/lib/qjsc_20210327.node' (no such file)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/Users/wangk/Desktop/elongHotel/kraken/bridge/polyfill/node_modules/bindings/bindings.js:112:48)
    at new Qjsc (/Users/wangk/Desktop/elongHotel/kraken/bridge/polyfill/node_modules/qjsc/index.js:9:41)
    at Object.<anonymous> (/Users/wangk/Desktop/elongHotel/kraken/bridge/polyfill/scripts/js_to_c.js:7:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  code: 'ERR_DLOPEN_FAILED'
}
/Users/wangk/Desktop/elongHotel/kraken/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 1,
  name: 'compile-polyfill',
  branch: false,
  error: 1,
  duration: [ 2, 136968500 ],
  time: 1646647686344
})
    at new NodeError (node:internal/errors:371:5)
    at Gulp.emit (node:events:509:17)
    at Gulp.emit (node:domain:475:12)
    at Object.error (/Users/wangk/Desktop/elongHotel/kraken/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/wangk/Desktop/elongHotel/kraken/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/wangk/Desktop/elongHotel/kraken/node_modules/once/once.js:25:25)
    at f (/Users/wangk/Desktop/elongHotel/kraken/node_modules/once/once.js:25:25)
    at tryCatch (/Users/wangk/Desktop/elongHotel/kraken/node_modules/async-done/index.js:24:15)
    at done (/Users/wangk/Desktop/elongHotel/kraken/node_modules/async-done/index.js:40:12)
    at /Users/wangk/Desktop/elongHotel/kraken/scripts/tasks.js:257:12 {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 1,
    name: 'compile-polyfill',
    branch: false,
    error: 1,
    duration: [ 2, 136968500 ],
    time: 1646647686344
  }
}

**预期结果 ｜ Expected results:** 
在非m1中可以，m1中有问题

**Comment by airingursb** [comment]
terminal 用 reosetta 转译后再打开，之后在这个转译后的 terminal 执行脚本就没有问题了

**Comment by WK726** [comment]
> terminal 用 reosetta 转译后再打开，之后在这个转译后的 terminal 执行脚本就没有问题了

完美解决
