### ISSUE TITLE
当多个自定义元素都使用了children时，嵌套使用时报错

### ISSUE THREAD

**Issue by donfo** [openkraken/kraken#1292]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

v0.10.2+1

### 重现步骤 ｜ Steps To Reproduce

当多个自定义元素都使用了children时，嵌套使用时报错：
```dart
'package:flutter[/src/foundation/node.dart]()': Failed assertion: line 128 pos 12: 'child._parent == null': is not true.
package:flutter/…/foundation/node.dart:128
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  [https://github.com/flutter/flutter/issues/new?template=2_bug.md]()

The relevant error-causing widget was
Container
lib/…/elements/index.dart:44
When the exception was thrown, this was the stack
#2      AbstractNode.adoptChild
package:flutter/…/foundation/node.dart:128
#3      RenderObject.adoptChild
package:flutter/…/rendering/object.dart:1337
#4      ContainerRenderObjectMixin.insert
package:flutter/…/rendering/object.dart:3312
#5      MultiChildRenderObjectElement.insertRenderObjectChild
package:flutter/…/widgets/framework.dart:6273
#6      RenderObjectElement.attachRenderObject
package:flutter/…/widgets/framework.dart:5870
#7      RenderObjectElement.mount
package:flutter/…/widgets/framework.dart:5544
#8      KrakenElementToFlutterElementAdaptor.mount
package:kraken/…/widget/element_to_widget_adaptor.dart:32
#9      Element.inflateWidget
package:flutter/…/widgets/framework.dart:3673
#10     MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6333
#11     MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6344
#12     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3673
#13     MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6333
#14     MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6344
...     Normal element mounting (16 frames)
#30     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3673
#31     MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6333
#32     MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6344
...     Normal element mounting (4 frames)
#36     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3673
#37     MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6333
#38     MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6344
#39     _ViewportElement.mount
package:flutter/…/widgets/viewport.dart:222
...     Normal element mounting (92 frames)
#131    Element.inflateWidget
package:flutter/…/widgets/framework.dart:3673
#132    Element.updateChild
package:flutter/…/widgets/framework.dart:3425
#133    KrakenRenderObjectToWidgetElement._rebuild
package:kraken/…/widget/widget_to_element_adaptor.dart:136
#134    KrakenRenderObjectToWidgetElement.mount
package:kraken/…/widget/widget_to_element_adaptor.dart:106
#135    KrakenRenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
package:kraken/…/widget/widget_to_element_adaptor.dart:63
#136    BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2573
#137    KrakenRenderObjectToWidgetAdapter.attachToRenderTree
package:kraken/…/widget/widget_to_element_adaptor.dart:61
#138    WidgetElement._attachWidget
package:kraken/…/widget/widget_to_element_adaptor.dart:264
#139    WidgetElement.didAttachRenderer
package:kraken/…/widget/widget_to_element_adaptor.dart:203
#140    Element.attachTo
package:kraken/…/dom/element.dart:698
#141    Element.ensureChildAttached
package:kraken/…/dom/element.dart:736
#142    Element.didAttachRenderer
package:kraken/…/dom/element.dart:409
#143    Element.attachTo
package:kraken/…/dom/element.dart:698
#144    Element.appendChild
package:kraken/…/dom/element.dart:764
#145    KrakenViewController.insertAdjacentNode
package:kraken/…/launcher/controller.dart:536
#146    flushUICommand
package:kraken/…/bridge/to_native.dart:540
#147    initBridge.<anonymous closure>.<anonymous closure>
package:kraken/…/bridge/bridge.dart:42
#148    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
#149    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1080
#150    SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
#154    _invoke (dart:ui[/hooks.dart:166:10]())
#155    PlatformDispatcher._drawFrame (dart:ui[/platform_dispatcher.dart:270:5]())
#156    _drawFrame (dart:ui[/hooks.dart:129:31]())
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
I[/flutter]() (12464): 'package:flutter[/src/widgets/framework.dart]()': Failed assertion: line 2724 pos 16: 'element.widget.runtimeType != oldElement.widget.runtimeType': is not true.
package:flutter/…/widgets/framework.dart:2724
I[/flutter]() (12464): #0      _AssertionError._doThrowNew (dart:core-patch[/errors_patch.dart:46:39]())
I[/flutter]() (12464): #1      _AssertionError._throwNew (dart:core-patch[/errors_patch.dart:36:5]())
I[/flutter]() (12464): #2      BuildOwner._registerGlobalKey.<anonymous closure>
package:flutter/…/widgets/framework.dart:2724
I[/flutter]() (12464): #3      BuildOwner._registerGlobalKey
package:flutter/…/widgets/framework.dart:2728
I[/flutter]() (12464): #4      Element.mount
package:flutter/…/widgets/framework.dart:3479
I[/flutter]() (12464): #5      RenderObjectElement.mount
package:flutter/…/widgets/framework.dart:5528
I[/flutter]() (12464): #6      KrakenRenderObjectToWidgetElement.mount
package:kraken/…/widget/widget_to_element_adaptor.dart:105
I[/flutter]() (12464): #7      KrakenRenderObjectToWidgetAdapter.attachToRenderTree
package:kraken/…/widget/widget_to_element_adaptor.dart:58
I[/flutter]() (12464): #8      WidgetElement._attachWidget
package:kraken/…/widget/widget_to_element_adaptor.dart:264
I[/flutter]() (12464): #9
```

**Comment by answershuto** [comment]
提供一下 Demo 吧

**Comment by donfo** [comment]
@answershuto 
```dart
import 'package:flutter/material.dart';
import 'package:kraken/kraken.dart';

void main() {
  Kraken.defineCustomElement('custom-a', (context) {
    return CustomAElement(context);
  });
  Kraken.defineCustomElement('custom-b', (context) {
    return CustomBElement(context);
  });
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final bundleContent = '''
const div = document.createElement("div");
div.appendChild(document.createTextNode("你好"));
const a = document.createElement("custom-a");
const b = document.createElement("custom-b");
b.appendChild(div);
a.appendChild(b);
document.body.appendChild(a);
''';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Kraken(
          bundle: KrakenBundle.fromContent(bundleContent),
        ),
      ),
    );
  }
}

class CustomAElement extends WidgetElement {
  CustomAElement(context) : super(context);

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {
    return Container(width: 300, height: 300, color: Colors.red, child: Column(children: children));
  }
}

class CustomBElement extends WidgetElement {
  CustomBElement(context) : super(context);

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {
    return Container(width: 200, height: 200, color: Colors.green, child: Column(children: children));
  }
}
```
