### ISSUE TITLE
Canvas显示出错，Unhandled Exception: Exception: Invalid image dimensions.

### ISSUE THREAD

**Issue by 7fresh** [openkraken/kraken#1309]
### 版本0.11.0

加载js文件，代码如下：

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 
``` (function(){
  'use strict';
  let wrapper, canvas, ctx, width, height,
    Tau=Math.PI*2, PI180=Math.PI/180,
    systems=[];

  /* PlanetarySystem */
  let PlanetarySystem = function(id='pSys'){
    Object.defineProperty(this, 'id',               { value:id, writable:true} );
    Object.defineProperty(this, 'x',                { value:0, writable:true });
    Object.defineProperty(this, 'y',                { value:0, writable:true });
    Object.defineProperty(this, 'allBodies',        { value:[], writable:true });
    Object.defineProperty(this, 'allBodiesLookup',  { value:{}, writable:true });    // fast id lookup for children
    Object.defineProperty(this, 'numBodies',        { value:0, writable:true });
  }
  PlanetarySystem.prototype.addBody = function(vo) {
    vo.parentSystem = this;
    vo.parentBody = vo.parentBody === null ? this : this.allBodiesLookup[vo.parentBody];
    let body = new PlanetaryBody(vo);
    body.update();
    this.allBodies.push(body);
    this.allBodiesLookup[vo.id] = body;
    this.numBodies += 1;
  }
  PlanetarySystem.prototype.setSpeedFactor = function(value){
    let body;
    for(let i=0; i<this.numBodies; i++){
      body = this.allBodies[i];
      body.setSpeedFactor(value);
    }
  }
  PlanetarySystem.prototype.update = function(){
    let body;
    for(let i=0; i<this.numBodies; i++){
      body = this.allBodies[i];
      body.update();
    }
  }
  /* PlanetaryBody */
  let PlanetaryBody = function(vo){
    Object.defineProperty(this, 'id',					{ value:vo.id, writable:true} );
    Object.defineProperty(this, 'diameter',				{ value:vo.diameter, writable:true });
    Object.defineProperty(this, 'colour',				{ value:vo.colour, writable:true });
    Object.defineProperty(this, 'x',					{ value:0, writable:true });
    Object.defineProperty(this, 'y',					{ value:0, writable:true });
    Object.defineProperty(this, 'vx',					{ value:0, writable:true });
    Object.defineProperty(this, 'vy',					{ value:0, writable:true });
    Object.defineProperty(this, 'degrees',				{ value:vo.degrees, writable:true });
    Object.defineProperty(this, 'speedBase',			{ value:vo.speed, writable:true });
    Object.defineProperty(this, 'speed',				{ value:vo.speed , writable:true });
    Object.defineProperty(this, 'orbitalRadius',		{ value:vo.orbitalRadius, writable:true });
    Object.defineProperty(this, 'parentSystem',			{ value:vo.parentSystem, writable:true });
    Object.defineProperty(this, 'parentBody',			{ value:vo.parentBody, writable:true });

    return this;
  }
  PlanetaryBody.prototype.update = function(){
    let angle = this.degrees * PI180;
    this.degrees += this.speed;
    this.vx = this.orbitalRadius * Math.cos(angle);
    this.vy = this.orbitalRadius * Math.sin(angle);
    // update position
    if(this.parentBody != null){
      this.x = this.vx + this.parentBody.x;
      this.y = this.vy + this.parentBody.y;
    }
  }

  /* init() */
  function init(){
    var wrapper = document.createElement('div');
    wrapper.style.background = '#111';
    document.body.appendChild(wrapper);
    canvas = createCanvas('canvas', width, height);
    wrapper.appendChild(canvas);
    ctx = canvas.getContext('2d');
    setupEvents();
    resizeCanvas();

    /* Define new PlanetarySystem and set values */
    let system1 = new PlanetarySystem('pSys1');
    systems.push(system1);
    system1.x = width * .5;
    system1.y = height * .5;
    system1.addBody({id:'sun', diameter:5, degrees:0, speed:0, colour:'#FDFE1D', orbitalRadius:0, parentBody:null});
    for(let loop=30, i=0; i<loop; i+=1){
      system1.addBody({	id:				'ball'+i,
        diameter:		5,
        degrees:		0,
        speed:			2 + (loop * 0.15) - (i* 0.2),
        colour:			'#FDFE1D',
        orbitalRadius:	7*(i+1),
        parentBody:		'sun'});
    }
  }

  /* Methods */
  function createCanvas(id, w, h){
    let tCanvas = document.createElement('canvas');
    tCanvas.width = w;
    tCanvas.height = h;
    tCanvas.id = id;
    return tCanvas;
  }

  function setupEvents(){
    window.onresize = resizeCanvas;
  }
  function resizeCanvas(){
    // let rect = wrapper.getBoundingClientRect();
    width = 300;
    height = 300;
    canvas.width = width;
    canvas.height = height;
    for(let i=0; i<systems.length; i++){
      systems[i].x = width * .5;
      systems[i].y = height * .5;
    }
  }

  function update(){
    for(let loop=systems.length, i=0; i<loop; i++){
      systems[i].update();
    }
  }

  function draw(){
    let system;
    let prev = null;
    for(let i=0; i<systems.length; i++){
      system = systems[i];
      let planetaryBody;
      for(let loop=system.numBodies, j=1; j<loop; j+=1) {
        planetaryBody = system.allBodies[j];
        ctx.beginPath();
        ctx.arc(planetaryBody.x, planetaryBody.y, planetaryBody.diameter, 0, Tau, false);
        ctx.fillStyle = planetaryBody.colour;
        ctx.fill();
        if(j>1){
          ctx.strokeStyle = planetaryBody.colour;
          ctx.lineWidth = 2;
          ctx.beginPath();
          ctx.moveTo(planetaryBody.x, planetaryBody.y);
          ctx.lineTo(prev.x, prev.y);
          ctx.stroke();
        }
        prev = {x:planetaryBody.x, y:planetaryBody.y};
      }
    }
  }

  function animate(){
    ctx.fillStyle = 'rgba(0,0,0, .05)';
    ctx.fillRect(0, 0, width, height);
    update();
    draw();
    requestAnimationFrame(animate);
  }
  init();
  animate();

}());

```

**预期结果 ｜ Expected results:** 
>  显示如图  ![WX20220411-000556@2x.png](https://inews.gtimg.com/newsapp_ls/0/14727953922/0.jiketuchuang.png)
**实际结果 ｜ Actual results:** 
> Unhandled Exception: Exception: Invalid image dimensions.
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Exception: Invalid image dimensions.
#0      Picture.toImage (dart:ui/painting.dart:5098:7)
#1      CanvasPainter.paint (package:kraken/src/dom/elements/canvas/canvas_painter.dart:86:31)
#2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:13)
#3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#5      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#6      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#7      PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198:7)
#8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185:7)
#9      RenderReplaced.performPaint (package:kraken/src/rendering/replaced.dart:150:15)
#10     RenderBoxModel._chainPaintO<…>
```
辛苦看看

**Comment by wssgcg1213** [comment]
我没看到你的图片地址? 如果 canvas 的面积 == 0, 会抛出这个错误, 你需要设置一个有效的 width 和 height

**Comment by wssgcg1213** [comment]
查到原因了, 是因为 resizeCanvas 的时候会重新创建 context2d, Dart 侧对象的指针没有更新, 我们这边处理一下

**Comment by wssgcg1213** [comment]
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/3922719/162661022-7f82044f-cbca-4654-9597-da9f97d496c4.png">
OK 了, 等下我提个 PR, 你可以用 PR 合入之日当天晚上发布的 nightly 版本验证

**Comment by 7fresh** [comment]
Awesome PR! 小姐姐太棒了！~
