### ISSUE TITLE
mac安装失败

### ISSUE THREAD

**Issue by okFancy** [openkraken/kraken#1433]
貌似是没有下载成功就执行了tar解压命令
尝试过 `sudo npm install -g @openkraken/cli --unsafe-perm `和 `sudo npm install -g @openkraken/cli`
### 安装失败日志：
```
$ sudo npm install -g @openkraken/cli --unsafe-perm
Password:
npm ERR! code 1
npm ERR! path /Users/mapc/.npm-global/lib/node_modules/@openkraken/cli
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
npm ERR!                                  Dload  Upload   Total   Spent    Left  Speed
100   273  100   273    0     0   1101      0 --:--:-- --:--:-- --:--:--  1151
npm ERR! tar: Error opening archive: Unrecognized archive format
npm ERR! child_process.js:866
npm ERR!     throw err;
npm ERR!     ^
npm ERR!
npm ERR! Error: Command failed: tar xzf /Users/mapc/.npm-global/lib/node_modules/@openkraken/cli/kraken-darwin-0.10.5.tar.gz -C ./build
npm ERR!     at checkExecSyncError (child_process.js:790:11)
npm ERR!     at execSync (child_process.js:863:15)
npm ERR!     at Object.<anonymous> (/Users/mapc/.npm-global/lib/node_modules/@openkraken/cli/install.js:15:1)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
npm ERR!     at internal/main/run_main_module.js:17:47 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [ null, null, null ],
npm ERR!   pid: 61042,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
```

**预期结果 ｜ Expected results:** 
正常安装

**实际结果 ｜ Actual results:** 
安装失败，提示：
``` 
Error: Command failed: tar xzf /Users/mapc/.npm-global/lib/node_modules/@openkraken/cli/kraken-darwin-0.10.5.tar.gz -C ./build
```

**Comment by cnryb** [comment]
和 #1428  是相同问题了，这个就先关掉了
