### ISSUE TITLE
安装 Kraken CLI 报错

### ISSUE THREAD

**Issue by wanglinjiang** [openkraken/kraken#190]
Mac 系统版本 MacOS BigSur  11.2.3
Node 版本 14.16.1
NPM 版本  6.14.12

执行命令  sudo  npm install -g @openkraken/cli 
报错如下：
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file kraken-darwin-0.7.2.tar.gz: Permission 
Warning: denied
  0 57.2M    0   926    0     0   1295      0 12:52:39 --:--:-- 12:52:39  1293
curl: (23) Failed writing body (0 != 926)
child_process.js:655
    throw err;
    ^

Error: Command failed: curl -O https://kraken.oss-cn-hangzhou.aliyuncs.com/kraken-cli-vendors/kraken-darwin-0.7.2.tar.gz
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/@openkraken/cli/install.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 23,
  signal: null,
  output: [ null, null, null ],
  pid: 20726,
  stdout: null,
  stderr: null
}
```

**Comment by andycall** [comment]
看样子是 npm 禁止 root 用户写入文件导致的，

可以使用下面的方式安装：

```
sudo npm install -g @openkraken/cli --unsafe-perm
```

**Comment by andycall** [comment]
或者按照下面的方式将 node 安装在用户目录，这样就不需要 sudo 了

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
