### ISSUE TITLE
macOS 安装 Kraken CLI失败

### ISSUE THREAD

**Issue by Leopold1988** [openkraken/kraken#217]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Kraken:0.7.1
node:12.19.0
npm:6.14.6

---

### 重现步骤 ｜ Steps To Reproduce

安装Kraken CLI

---

**重现代码 | Code example:** 

```shell
sudo npm install -g @openkraken/cli
```

---

**预期结果 ｜ Expected results:** 
正常安装

---

**实际结果 ｜ Actual results:** 

安装失败

```shell
> @openkraken/cli@0.7.2 postinstall /usr/local/lib/node_modules/@openkraken/cli
> node install.js

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file kraken-darwin-0.7.2.tar.gz: Permission 
Warning: denied
  0 57.2M    0   926    0     0   4797      0  3:28:35 --:--:--  3:28:35  4797
curl: (23) Failed writing body (0 != 926)
child_process.js:674
    throw err;
    ^

Error: Command failed: curl -O https://kraken.oss-cn-hangzhou.aliyuncs.com/kraken-cli-vendors/kraken-darwin-0.7.2.tar.gz
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/@openkraken/cli/install.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 23,
  signal: null,
  output: [ null, null, null ],
  pid: 14583,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @openkraken/cli@0.7.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @openkraken/cli@0.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pengli/.npm/_logs/2021-04-25T06_54_50_725Z-debug.log
```

**Comment by cos2004** [comment]
遇到同样问题

**Comment by yumeiqiang** [comment]
提问之前先翻翻之前的issues，之前有说过这个问题的 sudo npm install -g @openkraken/cli --unsafe-perm

**Comment by Leopold1988** [comment]
@@@我的是权限的问题，刚刚解决了，如果大家也有这样的问题可以参考一下（不一定能解决你的问题）@cos2004：
```shell
sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) /usr/local/lib
sudo chown -R $(whoami) /usr/local/bin
```

**Comment by chenyulun** [comment]
我的出现了
Kraken Binary NOT exists, try reinstall.

应该是我禁止了脚本的执行，
cd到安装目录然后执行
`npm run postinstall`就可以安装二进制包了

**Comment by wssgcg1213** [comment]
cc #105 #190

**Comment by wssgcg1213** [comment]
> 文档可以更新一下吗，很多人就是看到了安装命令直接敲的。
> 我的是权限的问题，刚刚解决了，如果大家也有这样的问题可以参考一下（不一定能解决你的问题）@cos2004：
> 
> ```shell
> sudo chown -R $(whoami) ~/.npm
> sudo chown -R $(whoami) /usr/local/lib
> sudo chown -R $(whoami) /usr/local/bin
> ```

感谢建议, 我们会增加一个常见问题解答的页面 cc @answershuto

**Comment by wssgcg1213** [comment]
https://github.com/openkraken/website/issues/124
