### ISSUE TITLE
flutter: NoSuchMethodError: The method 'send' was called on null.

### ISSUE THREAD

**Issue by andycall** [openkraken/kraken#237]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.7.1

### 重现步骤 ｜ Steps To Reproduce

react demo

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:** 

```
flutter: Observatory listening on http://127.0.0.1:63511/EkK-XGzMDXo=/
flutter: NoSuchMethodError: The method 'send' was called on null.
Receiver: null
Tried calling: send(Instance of 'DOMUpdatedEvent')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      UIInspector.onDOMTreeChanged (package:kraken/src/inspector/ui_inspector.dart:101:38)
#2      ElementManager._debugDOMTreeChanged (package:kraken/src/dom/element_manager.dart:486:26)
#3      ElementManager.insertAdjacentNode (package:kraken/src/dom/element_manager.dart:380:5)
#4      KrakenViewController.insertAdjacentNode (package:kraken/src/launcher/controller.dart:320:21)
#5      flushUICommand (package:kraken/src/bridge/to_native.dart:393:29)

```

**Comment by Leopold1988** [comment]
这个错同样遇到，怎么解决。

**Comment by joliu1019** [comment]
同样遇到，Vue Sample工程。

**Comment by andycall** [comment]
在 0.7.3 版本的 cli 中修复，请安装最新版本
