### ISSUE TITLE
yarn start 找不到动态库 libkraken_devtools_jsc.dylib

### ISSUE THREAD

**Issue by luwuer** [openkraken/kraken#357]
### 使用的 Kraken 版本 
286396a0f

0.7.2+5-dev.1

### 使用的 Flutter 版本 
1.22.0
```
Flutter 1.22.0 • channel unknown • unknown source
Framework • revision d408d302e2 (8 months ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0
```

### 重现步骤

**重现代码**
```bash
cd kraken/example
flutter run
```

**预期结果**
可以在模拟器中预览 example 项目不报错

**实际结果**
example 应用确实安装到模拟器上了，但是报错找不到动态库 libkraken_devtools_jsc.dylib
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen(libkraken_devtools_jsc.dylib, 1): image not found)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      nativeDynamicLibrary (package:kraken_devtools/bridge/platform.dart:24:20)
#3      nativeDynamicLibrary (package:kraken_devtools/bridge/platform.dart)
#4      _registerDartMethods (package:kraken_devtools/bridge/from_native.dart:29:5)
#5      _registerDartMethods (package:kraken_devtools/bridge/from_native.dart)
#6      registerUIDartMethodsToCpp (package:kraken_devtools/bridge/from_native.dart:35:3)
#7      ChromeDevToolsService.init (package:kraken_devtools/kraken_devtools.dart:77:5)
#8      new KrakenController (package:kraken/src/launcher/controller.dart:496:23)
#9      _KrakenRenderObjectWidget.createRenderObject (package:kraken/widget.dart:159:35)
#10     RenderObjectElemen<…>
```

**Comment by andycall** [comment]
devtools还没有ios构建版本，后面会有，
现在可以先移除 kraken_devtools的依赖

**Comment by andycall** [comment]
这个报错现在已经可以自动避免， ios 平台下目前无法支持 devtools。
