### ISSUE TITLE
安卓模拟器打开空白，调试显示dlopen failed: library "libkraken_websocket_jsc.so" not found

### ISSUE THREAD

**Issue by cielyic** [openkraken/kraken#415]
### 重现步骤 ｜ Steps To Reproduce

- git clone kraken
- 打开安卓模拟器（Android9.0）
- npm run start
- 打开空白
- 调试显示

```

Warning: You are using these overridden dependencies:                   
! kraken 0.8.0-dev.1 from path ..                                       
Running "flutter pub get" in example...                             4.9s
Using hardware rendering with device AOSP on IA Emulator. If you notice graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
注: /Users/yichao/flutter/.pub-cache/hosted/pub.dartlang.org/jsc-0.2.0/android/src/main/java/com/example/jsc/JscPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                  
注: /Users/yichao/workplace/kraken/kraken/android/src/main/java/com/openkraken/kraken/KrakenPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                  
注: /Users/yichao/flutter/.pub-cache/hosted/pub.dartlang.org/kraken_websocket-0.2.0-dev.2/android/src/main/java/com/example/kraken_websocket/KrakenWebsocketPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                  
注: /Users/yichao/flutter/.pub-cache/hosted/pub.dartlang.org/kraken_devtools-0.2.0-dev.1/android/src/main/java/com/example/kraken_devtools/KrakenDevtoolsPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                  
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        40.1s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 8.6s
E/flutter (10808): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libkraken_websocket_jsc.so': dlopen failed: library "libkraken_websocket_jsc.so" not found
E/flutter (10808): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter (10808): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter (10808): #2      nativeDynamicLibrary (package:kraken_websocket/platform.dart:20:20)
E/flutter (10808): #3      nativeDynamicLibrary (package:kraken_websocket/platform.dart)
E/flutter (10808): #4      _initBridge (package:kraken_websocket/kraken_websocket.dart:10:1)
E/flutter (10808): #5      _initBridge (package:kraken_websocket/kraken_websocket.dart)
E/flutter (10808): #6      initBridge (package:kraken_websocket/kraken_websocket.dart:13:3)
E/flutter (10808): #7      KrakenWebsocket.initialize (package:kraken_websocket/kraken_websocket.dart:18:5)
E/flutter (10808): #8      main (package:kraken_example/main.dart:8:19)
E/flutter (10808): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter (10808): #10     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (10808): #11     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (10808): #12     _runZoned (dart:async/zone.dart:1789:10)
E/flutter (10808): #13     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter (10808): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter (10808): #15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (10808): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (10808): 
Syncing files to device AOSP on IA Emulator...                     399ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on AOSP on IA Emulator is available at: http://127.0.0.1:50117/FXCWznGWwGM=/
The Flutter DevTools debugger and profiler on AOSP on IA Emulator is available at:
http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A50117%2FFXCWznGWwGM%3D%2F


```

请问遇到这种情况要怎么处理

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by andycall** [comment]
不支持 android 模拟器，请使用真机

**Comment by cielyic** [comment]
> 不支持 android 模拟器，请使用真机

那这调试有点麻烦 有没有别的办法

**Comment by andycall** [comment]
iOS 支持模拟器

**Comment by cielyic** [comment]
> iOS 支持模拟器

我们的用户主要是Android，那这个以后会支持嘛，大概什么时候

**Comment by andycall** [comment]
暂时没有计划，使用真机就可以了。

**Comment by cielyic** [comment]
> 暂时没有计划，使用真机就可以了。

好的
