### ISSUE TITLE
example 在下面这些安卓机型运行问题

### ISSUE THREAD

**Issue by cielyic** [openkraken/kraken#418]
### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

1. Redmi 9A (mobile) • 9XGQ8TFY9TY9K77L • android-arm    • Android 10 (API 29)  
- 加载http://kraken.oss-cn-hangzhou.aliyuncs.com/demo/demo-rax.js闪退
```
I/GED     (12912): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
I/.kraken_exampl(12912): ProcessProfilingInfo new_methods=517 is saved saved_to_disk=1 resolve_classes_delay=8000
F/libc    (12912): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x61736964 in tid 12943 (1.ui), pid 12912 (.kraken_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/dandelion/dandelion:10/QP1A.190711.020/V12.0.9.0.QCDCNXM:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2021-06-15 14:06:35+0800
pid: 12912, tid: 12943, name: 1.ui  >>> com.openkraken.kraken_example <<<
uid: 10206
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x61736964
    r0  c9b968d8  r1  ba7f0000  r2  bbb819d0  r3  00000001
    r4  00000000  r5  61736964  r6  c9b968d8  r7  bbbcf768
    r8  e3dee500  r9  ba7f0000  r10 c9b96770  r11 c9b9677c
    ip  bdca4e30  sp  c9b96758  lr  bd7975e5  pc  61736964
backtrace:
      #00 pc 61736964  <unknown>
      #01 pc 000cd5e3  /data/app/com.openkraken.kraken_example-F0yBtga0K23pmjdBTuFf8g==/lib/arm/libjsc.so (BuildId: c7808440d63e8af5f7d119d1109db8dd3804d8f5)
      #02 pc 00223c01  /data/app/com.openkraken.kraken_example-F0yBtga0K23pmjdBTuFf8g==/lib/arm/libjsc.so (BuildId: c7808440d63e8af5f7d119d1109db8dd3804d8f5)
      #03 pc 0020e3c3  /data/app/com.openkraken.kraken_example-F0yBtga0K23pmjdBTuFf8g==/lib/arm/libjsc.so (BuildId: c7808440d63e8af5f7d119d1109db8dd3804d8f5)
Lost connection to device.
```
2. Vivo Z5x 712版 (mobile) • 15db77e7 • android-arm64  • Android 10 (API 29) 
 - 加载http://kraken.oss-cn-hangzhou.aliyuncs.com/demo/demo-rax.js成功
 - 加载本地项目成功
 - 本地项目热更新失败
 ```
The Flutter DevTools debugger and profiler on V1990A is available at:
http://127.0.0.1:9103?uri=http%3A%2F%2F127.0.0.1%3A55786%2Fel1ZFUd8rMY%3D%2F
D/NetdClient(14784): netdClientConnect netId:0, uid:10009, nid:-1, addr:192.168.31.5, lan:1, localhost:0, sa_family:2, sockfd:88, thread:
I/flutter (14784): Kraken DevTool listening at ws://192.168.31.122:9222
I/flutter (14784): Open Chrome/Edge and paste following url to your navigator:
I/flutter (14784):     devtools://devtools/bundled/inspector.html?ws=192.168.31.122:9222
D/NetdClient(14784): netdClientConnect netId:0, uid:10009, nid:-1, addr:192.168.31.5, lan:1, localhost:0, sa_family:2, sockfd:90, thread:
D/NetdClient(14784): queryResolvNetidForUid nid:0, uid:10009, command.cmdId:12
E/NetdClient(14784): querySockNetidForUid nid:0, uid:10009, command.cmdId:11, id:0
D/NetdClient(14784): netdClientConnect netId:0, uid:10009, nid:0, addr:27.148.162.253, lan:0, localhost:0, sa_family:2, sockfd:89, thread:1.ui
E/NetdClient(14784): querySockNetidForUid nid:0, uid:10009, command.cmdId:11, id:0
D/NetdClient(14784): netdClientConnect netId:0, uid:10009, nid:0, addr:27.148.162.254, lan:0, localhost:0, sa_family:2, sockfd:91, thread:1.ui
E/flutter (14784): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: LateInitializationError: Field '_contextId@778280329' has not been initialized.
E/flutter (14784): #0      KrakenViewController._contextId (package:kraken/src/launcher/controller.dart)
E/flutter (14784): #1      new KrakenViewController (package:kraken/src/launcher/controller.dart:136:18)
E/flutter (14784): #2      KrakenController.unload (package:kraken/src/launcher/controller.dart:539:13)
E/flutter (14784): <asynchronous suspension>
E/flutter (14784): #3      KrakenController.reload (package:kraken/src/launcher/controller.dart:555:5)
E/flutter (14784): <asynchronous suspension>
E/flutter (14784): 
```
3. Redmi 8A (mobile) • 0e7833d50006 • android-arm    • Android 9 (API 28)
-  加载http://kraken.oss-cn-hangzhou.aliyuncs.com/demo/demo-rax.js闪退
```
The Flutter DevTools debugger and profiler on Redmi 8A is available at:
http://127.0.0.1:9104?uri=http%3A%2F%2F127.0.0.1%3A57138%2FpwkUm911vHM%3D%2F
F/libc    (13238): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x61736964 in tid 13260 (1.ui), pid 13238 (.kraken_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/olivelite/olivelite:9/PKQ1.190319.001/V11.0.10.0.PCPCNXM:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 13238, tid: 13260, name: 1.ui  >>> com.openkraken.kraken_example <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x61736964
    r0  97c4e028  r1  8adf0000  r2  8c1819d0  r3  00000001
    r4  00000000  r5  61736964  r6  97c4e028  r7  8c1cf768
    r8  8caf52f0  r9  8adf0000  r10 97c4dec0  r11 97c4decc
    ip  8dde7e30  sp  97c4dea8  lr  8d8da5e5  pc  61736964
backtrace:
    #00 pc 61736964  <unknown>
    #01 pc 000cd5e3  /data/app/com.openkraken.kraken_example-jTTNHGvQU5-4vlgZmXLyUg==/lib/arm/libjsc.so
    #02 pc 00223c01  /data/app/com.openkraken.kraken_example-jTTNHGvQU5-4vlgZmXLyUg==/lib/arm/libjsc.so
    #03 pc 0020e3c3  /data/app/com.openkraken.kraken_example-jTTNHGvQU5-4vlgZmXLyUg==/lib/arm/libjsc.so
Lost connection to device.
```
4. 魅族PRO 5 (mobile) • 860BCMP228NY • android-arm64  • Android 7.0 (API 24) (emulator)
 - 加载http://kraken.oss-cn-hangzhou.aliyuncs.com/demo/demo-rax.js成功
 - 加载本地项目成功
 - 本地项目热更新失败
5. 华为Nove6SE (mobile) • MYQUT20320010103 • android-arm64  • Android 10 (API 29)
 - 加载http://kraken.oss-cn-hangzhou.aliyuncs.com/demo/demo-rax.js成功
 - 加载本地项目失败- 无报错
 - 本地项目热更新失败-无报错
6. 华为Mate30 (mobile) • GCL5T19C05022999 • android-arm64  • Android 10 (API 29)
 - 加载http://kraken.oss-cn-hangzhou.aliyuncs.com/demo/demo-rax.js成功
 - 加载本地项目成功
 - 本地项目热更新失败

**实际结果 ｜ Actual results:**

**Comment by andycall** [comment]
感谢反馈，热更新确实存在问题，我已经发现了，正在修复中

**Comment by andycall** [comment]
看上去 android-arm 架构的手机都会 crash，我看下为啥

**Comment by andycall** [comment]
热更新的问题修复了 https://github.com/openkraken/kraken/pull/419
