### ISSUE TITLE
iOS模拟器/真机打开空白，提示`libkraken_devtools_jsc.dylib`

### ISSUE THREAD

**Issue by cielyic** [openkraken/kraken#420]
### 重现步骤 ｜ Steps To Reproduce

- 没有任何修改的Kraken
- flutter run

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libkraken_devtools_jsc.dylib': dlopen(libkraken_devtools_jsc.dylib, 1): image not found
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      nativeDynamicLibrary (package:kraken_devtools/bridge/platform.dart:24:20)
#3      nativeDynamicLibrary (package:kraken_devtools/bridge/platform.dart)
#4      _registerDartMethods (package:kraken_devtools/bridge/from_native.dart:29:5)
#5      _registerDartMethods (package:kraken_devtools/bridge/from_native.dart)
#6      registerUIDartMethodsToCpp (package:kraken_devtools/bridge/from_native.dart:35:3)
#7      ChromeDevToolsService.init (package:kraken_devtools/kraken_devtools.dart:77:5)
#8      new KrakenController (package:kraken/src/launcher/controller.dart:516:24)
#9      _KrakenRenderObjectWidget.createRenderObject (package:kraken/widget.dart:150:<…>
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: LateInitializationError: Field '_contextId@778280329' has not been initialized.
#0      KrakenViewController._contextId (package:kraken/src/launcher/controller.dart)
#1      new KrakenViewController (package:kraken/src/launcher/controller.dart:135:18)
#2      KrakenController.unload (package:kraken/src/launcher/controller.dart:561:13)
<asynchronous suspension>
#3      Kraken.loadURL (package:kraken/widget.dart:71:5)
<asynchronous suspension>

```

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by andycall** [comment]
iOS 下还不支持 devtools，需要移除 kraken_devtools 的依赖

**Comment by cielyic** [comment]
> iOS 下还不支持 devtools，需要移除 kraken_devtools 的依赖

好的
