### ISSUE TITLE
有可用的slider组件吗（rax-slider不好用）

### ISSUE THREAD

**Issue by xmsz** [openkraken/kraken#513]
## 使用场景 ｜ Use case
- 项目中很经常要用到slider组件
- 正常第三方的slider组件估计都用不了，毕竟太庞大而复杂
- 使用rax-slider则表现很差

rax-slider表现
- 划2下就挂了
```
<Swiper
      width="750"
      height="310"
    >
      <Swiper.Item>1</Swiper.Item>
      <Swiper.Item>2</Swiper.Item>
    </Swiper>
```

```
undefined is not an object (evaluating '_this.childRefs[_this.index === _this.total - 1 ? 0 : _this.index + 1].current')
http://192.168.1.83:3333/kraken/static/screenshot.js:4975:77
onPanResponderMove@http://192.168.1.83:3333/kraken/static/screenshot.js:4613:31
onTouchMove@http://192.168.1.83:3333/kraken/static/screenshot.js:15465:36

flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following ConcurrentModificationError was thrown during a scheduler callback:
flutter: Concurrent modification during iteration: Instance(length:3) of '_GrowableList'.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ListIterator.moveNext (dart:_internal/iterable.dart:335:7)
flutter: #1      AnimationTimeline._getActiveAnimations (package:kraken/src/css/animation.dart:103:33)
flutter: #2      AnimationTimeline._onTick (package:kraken/src/css/animation.dart:89:19)
flutter: #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
flutter: #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1058:11)
flutter: #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
flutter: #7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056:17)
flutter: #8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:977:5)
flutter: #12     _invoke1 (dart:ui/hooks.dart:182:10)
flutter: #13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:237:5)
flutter: #14     _beginFrame (dart:ui/hooks.dart:114:31)
flutter: (elided 3 frames from dart:async)
flutter:
flutter:
flutter: This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
flutter: #2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:523:49)
flutter: #3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:253:47)
flutter: #4      Ticker.start (package:flutter/src/scheduler/ticker.dart:162:7)
flutter: #5      AnimationTimeline._addAnimation (package:kraken/src/css/animation.dart:120:15)
flutter: #6      Animation._ensureAlive (package:kraken/src/css/animation.dart:365:15)
flutter: #7      Animation.play (package:kraken/src/css/animation.dart:328:5)
flutter: #8      CSSStyleDeclaration._transition (package:kraken/src/css/style_declaration.dart:221:15)
flutter: #9      CSSStyleDeclaration.setProperty (package:kraken/src/css/style_declaration.dart:566:7)
flutter: #10     Element.setStyle (package:kraken/src/dom/element.dart:1153:13)
flutter: #11     ElementManager.setStyle (package:kraken/src/dom/element_manager.dart:247:14)
flutter: #12     KrakenViewController.setStyle (package:kraken/src/launcher/controller.dart:314:21)
flutter: #13     flushUICommand (package:kraken/src/bridge/to_native.dart:406:29)
flutter: #14     initBridge.<anonymous closure>.<anonymous closure> (package:kraken/src/bridge/bridge.dart:40:9)
flutter: #15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
flutter: #21     _invoke (dart:ui/hooks.dart:163:10)
flutter: #22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
flutter: #23     _drawFrame (dart:ui/hooks.dart:126:31)
flutter: (elided 5 frames from class _FrameCallbackEntry and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

## 提案 ｜ Proposal
- 修复rax-slider
- 有没有其他可用的slider组件

**Comment by xmsz** [comment]
rc-slider => 缺少react-dom
@boxslider/slider => Can't find variable: HTMLElement
自己写的超级精简版 => 卡得要死
只要给dom加上transition就会变得非常卡

**Comment by zishenWang** [comment]
同求这个基础组件swiper

**Comment by temper357** [comment]
rax-slider 在之前业务中可以正常使用，应该是新版本 animation 有 bug，我来看下
