### ISSUE TITLE
npm run build:bridge:all:release 执行失败

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#616]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
master

### 重现步骤 ｜ Steps To Reproduce
更新代码，执行 `npm run build:bridge:all:release` 

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 4,
  name: 'build-ios-kraken-lib',
  branch: false,
  error: Error: Command failed: mv /Users/renyuebing/Desktop/github/openkraken/kraken/bridge/build/ios/framework/kraken_bridge.framework/kraken_bridge.dSYM /Users/renyuebing/Desktop/github/openkraken/kraken/bridge/build/ios/framework
  mv: rename /Users/renyuebing/Desktop/github/openkraken/kraken/bridge/build/ios/framework/kraken_bridge.framework/kraken_bridge.dSYM to /Users/renyuebing/Desktop/github/openkraken/kraken/bridge/build/ios/framework/kraken_bridge.dSYM: Directory not empty
  
      at checkExecSyncError (child_process.js:643:11)
      at execSync (child_process.js:679:15)
      at /Users/renyuebing/Desktop/github/openkraken/kraken/scripts/tasks.js:426:5
      at build-ios-kraken-lib (/Users/renyuebing/Desktop/github/openkraken/kraken/node_modules/undertaker/lib/set-task.js:13:15)
      at bound (domain.js:416:15)
      at runBound (domain.js:427:12)
      at asyncRunner (/Users/renyuebing/Desktop/github/openkraken/kraken/node_modules/async-done/index.js:55:18)
      at processTicksAndRejections (internal/process/task_queues.js:77:11) {
    status: 1,
    signal: null,
    output: [
      null,
      <Buffer >,
      <Buffer 6d 76 3a 20 72 65 6e 61 6d 65 20 2f 55 73 65 72 73 2f 72 65 6e 79 75 65 62 69 6e 67 2f 44 65 73 6b 74 6f 70 2f 67 69 74 68 75 62 2f 6f 70 65 6e 6b 72 ... 203 more bytes>
    ],
    pid: 72848,
    stdout: <Buffer >,
    stderr: <Buffer 6d 76 3a 20 72 65 6e 61 6d 65 20 2f 55 73 65 72 73 2f 72 65 6e 79 75 65 62 69 6e 67 2f 44 65 73 6b 74 6f 70 2f 67 69 74 68 75 62 2f 6f 70 65 6e 6b 72 ... 203 more bytes>,
    domainThrown: true
  },
  duration: [ 38, 280225776 ],
  time: 1629685425366
})

```

**Comment by yuanyan** [comment]
执行 all:build 要确保所有环境都安装完成，建议先执行 macos的
