### ISSUE TITLE
sliver 列表，内容不显示异常

### ISSUE THREAD

**Issue by pba-cra** [openkraken/kraken#708]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 
异常情况
```
<style>
    body {
        width:100vw;
        height: 100vh;
        display: flex;
    }
    #outerContainer{
        display: flex;
        flex:1;
    }
    #content{
        display: sliver;
        flex:1;
    }
</style>
<body>
    <div id='outerContainer' >
        <div id='content'>
            <div>asfasdf</div>
            <div>adfadfa</div>
            <div>asfasdf</div>
            <div>adfadfa</div>
            <div>asfasdf</div>
            <div>adfadfa</div>
        </div>
    </div>
</body>
```
 修改#content为
```
  #content{
      display: sliver;
      width: 100%;
      height: 100%;
  }
```
显示正常

**预期结果 ｜ Expected results:** 
id为content中的子元素正常显示

**实际结果 ｜ Actual results:** 
id为content中的子元素 不显示，整个content是空白。

**Comment by wssgcg1213** [comment]
Hello, 你使用的是 main 分支还是 pub 上的版本?

**Comment by pba-cra** [comment]
使用的是main分支上的哈

**Comment by pba-cra** [comment]
> Hello, 你使用的是 main 分支还是 pub 上的版本?
使用的是main分支上的哈

**Comment by wssgcg1213** [comment]
👌  我看一下这个 case ~

**Comment by jingsarah** [comment]
请问这个问题解决了么？遇到了同样的内容不显示的问题

**Comment by mengxiangchengzhen8117** [comment]
升级到0.9.0后没有解决问题还报错了
flutter: Null check operator used on a null value
#0      RenderRecyclerLayout._buildRenderSliverList (package:kraken/src/rendering/recycler.dart:122:106)
#1      new RenderRecyclerLayout (package:kraken/src/rendering/recycler.dart:51:25)
#2      RenderFlowLayout.toRenderRecyclerLayout (package:kraken/src/rendering/flow.dart:1739:35)
#3      Element.createRenderLayout (package:kraken/src/dom/element.dart:1665:52)
#4      CSSDisplayMixin.updateDisplay (package:kraken/src/css/display.dart:53:32)
#5      Element._styleDisplayChangedListener (package:kraken/src/dom/element.dart:972:33)
#6      Element._onStyleChanged (package:kraken/src/dom/element.dart:810:9)
#7      CSSStyleDeclaration.setRenderStyleProperty (package:kraken/src/css/style_declaration.dart:757:15)
#8      CSSStyleDeclaration.setRenderStyle (package:kraken/src/css/style_declaration.dart:731:7)
#9      Element.setRenderStyle (package:kraken/src/dom/element.dart:1281:11)
#10     ElementManager.setRenderStyle 
(package:kraken/src/dom/element_manager.dart:293:14)
#11     KrakenViewController.setRenderStyle (package:kraken/src/launcher/controller.dart:322:21)
#12     flushUICommand (package:kraken/src/bridge/to_native.dart:507:25)
#13     initBridge.<anonymous closure>.<anonymous closure> (package:kraken/src/bridge/bridge.dart:43:9)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#17     _rootRun (dart:async/zone.dart:1354:13)
#18     _CustomZone.run (dart:async/zone.dart:1258:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#20     _invoke (dart:ui/hooks.dart:163:10)
#21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#22     _drawFrame (dart:ui/hooks.dart:126:31)

flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following _CastError was thrown during performLayout():
flutter: type 'Null' is not a subtype of type 'RenderLayoutParentData' in type cast
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderStyle.isPercentageOfSizingExist (package:kraken/src/css/render_style.dart:382:79)
flutter: #1      RenderFlowLayout._isChildrenPercentageOfSizingExist (package:kraken/src/rendering/flow.dart:1134:50)
flutter: #2      RenderFlowLayout._layoutChildren (package:kraken/src/rendering/flow.dart:982:38)
flutter: #3      RenderFlowLayout.performLayout (package:kraken/src/rendering/flow.dart:413:5)
flutter: #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
flutter: #5      RenderBoxModel.layout (package:kraken/src/rendering/box_model.dart:793:11)
flutter: #6      RenderFlowLayout._layoutChildren (package:kraken/src/rendering/flow.dart:616:15)
flutter: #7      RenderFlowLayout.performLayout (package:kraken/src/rendering/flow.dart:413:5)
flutter: #8      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636:7)
flutter: #9      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
flutter: #10     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
flutter: #11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
flutter: #12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
flutter: #18     _invoke (dart:ui/hooks.dart:163:10)
flutter: #19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
flutter: #20     _drawFrame (dart:ui/hooks.dart:126:31)
flutter: (elided 3 frames from dart:async)
flutter: 
flutter: The following RenderObject was being processed when the exception was fired: RenderSelfRepaintFlowLayout#1022a relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   needs compositing
flutter:   parentData: isPositioned=false; offset=Offset(0.0, 0.0); runIndex: 0; (can use size)
flutter:   constraints: BoxConstraints(360.0<=w<=Infinity, 640.0<=h<=Infinity)
flutter:   layer: OffsetLayer#09b5a
flutter:   size: Size(360.0, 640.0)
flutter:   contentSize: Size(360.0, 640.0)
flutter:   contentConstraints: BoxConstraints(360.0<=w<=Infinity, 640.0<=h<=Infinity)
flutter:   widthSizeType: BoxSizeType.automatic
flutter:   heightSizeType: BoxSizeType.automatic
flutter:   maxScrollableSize: Size(360.0, 640.0)
flutter:   clipX: false
flutter:   clipY: false
flutter:   transformOrigin: Offset(0.0, 0.0)
flutter:   transformAlignment: Alignment.center
flutter: This RenderObject had the following child:
flutter:     child 1: RenderFlowLayout#3bac5 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by mengxiangchengzhen8117** [comment]
1、这个sliver必须得操作dom动态创建元素节点，直接样式属性绑定会白屏
2、dom.style.display='sliver' 必须再次去设置一遍height即 dom.style.height='xxx' ,否则白屏
3、style变量初始值设置为sliver，偶现白屏，我是改为了mounted钩子中判断时kraken环境才设置为sliver，后续创建列表容器dom时再dom.style.display=this.style.list.display
4、dom.setAttribute('style', '');会报错虽然不影响渲染但是控制台会出现报错信息，所以得遍历后挨个设置dom.style[key]=this.style.list[key];
