### ISSUE TITLE
圆角和一个边的边框颜色组合无法渲染

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#797]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
main 分支

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:**

```JavaScript
const container = document.createElement('div')

container.textContent = '123'
container.style.border = '2px solid'
container.style.borderRadius = '100px'
container.style.borderLeftColor = 'red'

document.body.appendChild(container)
```

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:** 
渲染失败，展示白屏，命令行报如下错误：
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
A borderRadius can only be given for a uniform Border.
The following is not uniform:
BorderSide.color

When the exception was thrown, this was the stack:
#0      Border.paint.<anonymous closure> (package:flutter/src/painting/box_border.dart:523:9)
#1      Border.paint (package:flutter/src/painting/box_border.dart:532:6)
#2      BoxDecorationPainter.paint (package:kraken/src/rendering/box_decoration_painter.dart:466:25)
#3      RenderBoxDecorationMixin.paintDecoration (package:kraken/src/rendering/box_decoration.dart:101:17)
#4      RenderBoxModel._chainPaintDecoration (package:kraken/src/rendering/box_model.dart:1453:5)
#5      RenderOpacityMixin.paintOpacity (package:kraken/src/rendering/opacity.dart:22:15)
#6      RenderBoxModel._chainPaintOpacity (package:kraken/src/rendering/box_model.dart:1446:5)
#7      RenderTransformMixin.paintTransform (package:kraken/src/rendering/transform.dart:52:15)
#8      RenderBoxModel._chainPaintTransform (package:kraken/src/rendering/box_model.dart:1442:5)
#9      RenderIntersectionObserverMixin.paintIntersectionObserver (package:kraken/src/rendering/intersection_observer.dart:79:15)
#10     RenderBoxModel._chainPaintIntersectionObserver (package:kraken/src/rendering/box_model.dart:1438:5)
#11     RenderImageFilter.paintImageFilter (package:kraken/src/rendering/filter.dart:56:15)
#12     RenderBoxModel._chainPaintImageFilter (package:kraken/src/rendering/box_model.dart:1434:5)
#13     RenderColorFilter.paintColorFilter (package:kraken/src/rendering/filter.dart:30:15)
#14     RenderBoxModel.paintBoxModel (package:kraken/src/rendering/box_model.dart:1430:5)
#15     RenderBoxModel.paint (package:kraken/src/rendering/box_model.dart:1406:5)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#18     RenderFlowLayout.performPaint (package:kraken/src/rendering/flow.dart:1721:17)
#19     RenderBoxModel._chainPaintOverlay (package:kraken/src/rendering/box_model.dart:1502:5)
#20     RenderContentVisibilityMixin.paintContentVisibility (package:kraken/src/rendering/content_visibility.dart:26:13)
#21     RenderBoxModel._chainPaintContentVisibility (package:kraken/src/rendering/box_model.dart:1498:5)
#22     RenderOverflowMixin.paintOverflow (package:kraken/src/gesture/scrollable.dart:370:58)
#23     RenderBoxModel._chainPaintOverflow (package:kraken/src/rendering/box_model.dart:1484:7)
#24     RenderBoxModel._chainPaintDecoration (package:kraken/src/rendering/box_model.dart:1454:5)
#25     RenderOpacityMixin.paintOpacity (package:kraken/src/rendering/opacity.dart:22:15)
#26     RenderBoxModel._chainPaintOpacity (package:kraken/src/rendering/box_model.dart:1446:5)
#27     RenderTransformMixin.paintTransform (package:kraken/src/rendering/transform.dart:52:15)
#28     RenderBoxModel._chainPaintTransform (package:kraken/src/rendering/box_model.dart:1442:5)
#29     RenderIntersectionObserverMixin.paintIntersectionObserver (package:kraken/src/rendering/intersection_observer.dart:79:15)
#30     RenderBoxModel._chainPaintIntersectionObserver (package:kraken/src/rendering/box_model.dart:1438:5)
#31     RenderImageFilter.paintImageFilter (package:kraken/src/rendering/filter.dart:56:15)
#32     RenderBoxModel._chainPaintImageFilter (package:kraken/src/rendering/box_model.dart:1434:5)
#33     RenderColorFilter.paintColorFilter (package:kraken/src/rendering/filter.dart:30:15)
#34     RenderBoxModel.paintBoxModel (package:kraken/src/rendering/box_model.dart:1430:5)
#35     RenderBoxModel.paint (package:kraken/src/rendering/box_model.dart:1406:5)
#36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#38     RenderFlowLayout.performPaint (package:kraken/src/rendering/flow.dart:1721:17)
#39     RenderBoxModel._chainPaintOverlay (package:kraken/src/rendering/box_model.dart:1502:5)
#40     RenderContentVisibilityMixin.paintContentVisibility (package:kraken/src/rendering/content_visibility.dart:26:13)
#41     RenderBoxModel._chainPaintContentVisibility (package:kraken/src/rendering/box_model.dart:1498:5)
#42     RenderOverflowMixin.paintOverflow (package:kraken/src/gesture/scrollable.dart:370:58)
#43     RenderBoxModel._chainPaintOverflow (package:kraken/src/rendering/box_model.dart:1484:7)
#44     RenderBoxModel._chainPaintDecoration (package:kraken/src/rendering/box_model.dart:1454:5)
#45     RenderOpacityMixin.paintOpacity (package:kraken/src/rendering/opacity.dart:22:15)
#46     RenderBoxModel._chainPaintOpacity (package:kraken/src/rendering/box_model.dart:1446:5)
#47     RenderTransformMixin.paintTransform (package:kraken/src/rendering/transform.dart:52:15)
#48     RenderBoxModel._chainPaintTransform (package:kraken/src/rendering/box_model.dart:1442:5)
#49     RenderIntersectionObserverMixin.paintIntersectionObserver (package:kraken/src/rendering/intersection_observer.dart:79:15)
#50     RenderBoxModel._chainPaintIntersectionObserver (package:kraken/src/rendering/box_model.dart:1438:5)
#51     RenderImageFilter.paintImageFilter (package:kraken/src/rendering/filter.dart:56:15)
#52     RenderBoxModel._chainPaintImageFilter (package:kraken/src/rendering/box_model.dart:1434:5)
#53     RenderColorFilter.paintColorFilter (package:kraken/src/rendering/filter.dart:30:15)
#54     RenderBoxModel.paintBoxModel (package:kraken/src/rendering/box_model.dart:1430:5)
#55     RenderBoxModel.paint (package:kraken/src/rendering/box_model.dart:1406:5)
#56     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#57     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:139:11)
#58     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#59     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:975:29)
#60     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:464:19)
#61     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#62     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#63     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#64     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#65     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#69     _invoke (dart:ui/hooks.dart:163:10)
#70     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#71     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)

The following RenderObject was being processed when the exception was fired: RenderFlowLayout#4a7db relayoutBoundary=up3:
  parentData: isPositioned=false; offset=Offset(0.0, 0.0); runIndex: 0; (can use size)
  constraints: BoxConstraints(4.0<=w<=375.0, 4.0<=h<=Infinity)
  size: Size(375.0, 23.0)
  contentSize: Size(371.0, 19.0)
  contentConstraints: BoxConstraints(0.0<=w<=371.0, 0.0<=h<=Infinity)
  widthSizeType: BoxSizeType.automatic
  heightSizeType: BoxSizeType.automatic
  maxScrollableSize: Size(371.0, 19.0)
  borderEdge: EdgeInsets.all(2.0)
  backgroundClip: BackgroundBoundary.borderBox
  backgroundOrigin: BackgroundBoundary.paddingBox
  borderRadius: BorderRadius.circular(100.0)
  clipX: false
  clipY: false
  transformOrigin: Offset(0.0, 0.0)
  transformAlignment: Alignment.center
This RenderObject had the following descendants (showing up to depth 5):
    child 1: RenderTextBox#b17fd relayoutBoundary=up4 NEEDS-PAINT
      child: KrakenRenderParagraph#8afee relayoutBoundary=up5 NEEDS-PAINT
        text: TextSpan
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by wssgcg1213** [comment]
@temper357 any update?

**Comment by temper357** [comment]
没有快捷的兼容方案，这个是 flutter 已有的问题 https://github.com/flutter/flutter/issues/12583，如果要做的话，只能 Kraken 自己用自绘来实现

**Comment by cnryb** [comment]
如果仅把目标定为，渲染成功呢？

比如，按照上右下左的顺序，哪个有值就采用哪个的，把所有颜色设置相同。

**Comment by temper357** [comment]
可以，如果仅仅是为了不出错作 fallback 是可以采用这个方案。

**Comment by temper357** [comment]
https://github.com/openkraken/kraken/pull/656 分支已经作了兼容，当四个方向中 border 非 uniform 的情况下，border-radius 处理成不生效。同时官网文档中也增加了这个说明。

**Comment by cnryb** [comment]
👍

**Comment by cnryb** [comment]
fixed in #656
