### ISSUE TITLE
Vue 中 v-show 、v-if 监控的属性三次变换之后，功能失效

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#860]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
cli 0.9.0

### 重现步骤 ｜ Steps To Reproduce

点击三次之后，div 展示隐藏功能失效，并在控制台报如下信息
```
flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 3210 pos 12: 'child != after': A RenderObject cannot be inserted after itself.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:3210:12)
#3      RenderLayoutBox.insert (package:kraken/src/rendering/box_model.dart:190:11)
#4      Element.addChildRenderObject (package:kraken/src/dom/element.dart:577:33)
#5      Element.attachTo (package:kraken/src/dom/element.dart:600:14)
#6      Element.setStyle (package:kraken/src/dom/element.dart:1272:7)
#7      ElementManager.setStyle (package:kraken/src/dom/element_manager.dart:282:14)
#8      KrakenViewController.setStyle (package:kraken/src/launcher/controller.dart:312:21)
#9      flushUICommand (package:kraken/src/bridge/to_native.dart:481:29)
#10     initBridge.<anonymous closure>.<anonymous closure> (package:kraken/src/bridge/bridge.dart:43:9)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#14     _rootRun (dart:async/zone.dart:1354:13)
#15     _CustomZone.run (dart:async/zone.dart:1258:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#17     _invoke (dart:ui/hooks.dart:163:10)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#19     _drawFrame (dart:ui/hooks.dart:126:31)

```
**重现代码 | Code example:** 
异常的工程样例 https://github.com/cnryb/kraken-demo/blob/master/test-case/test-case12/src/App.vue
出现异常的代码
``` vue
<template>
  <button @click="toggle">toggle visibility</button>

  <div>fuck vShow: {{ show }}</div>
  <div v-if="show" style="padding: 20px; background: red; color: white">content</div>
</template>

<script setup>
import { ref } from 'vue'

const show = ref(false)

function toggle() {
  show.value = !show.value
}
</script>
```

**Comment by answershuto** [comment]
我在 main 上测试似乎没有复现 @cnryb

**Comment by cnryb** [comment]
我也复现不出来了。先关掉吧。
