### ISSUE TITLE
图片地址 解析异常

### ISSUE THREAD

**Issue by colorfulldays** [openkraken/kraken#869]
kraken 0.8.4 正常图片地址  被解析成  //assets/#/#/

。在0.7.3 和 。0.9.0上都可以正常显示

```
 FormatException: Invalid empty scheme (at character 1)
I/flutter (23979): ://assets/#/#/
I/flutter (23979): ^
I/flutter (23979): 
I/flutter (23979): #0      _Uri._fail (dart:core/uri.dart:1538:5)
I/flutter (23979): #1      new _Uri.notSimple (dart:core/uri.dart:1371:9)
I/flutter (23979): #2      Uri.parse (dart:core/uri.dart:956:17)
I/flutter (23979): #3      ImageElement._loadImage (package:kraken/src/dom/elements/img.dart:424:22)
I/flutter (23979): #4      ImageElement.setProperty (package:kraken/src/dom/elements/img.dart:387:7)
I/flutter (23979): #5      ElementManager.setProperty (package:kraken/src/dom/element_manager.dart:238:14)
I/flutter (23979): #6      KrakenViewController.setProperty (package:kraken/src/launcher/controller.dart:332:21)
I/flutter (23979): #7      flushUICommand (package:kraken/src/bridge/to_native.dart:479:29)
I/flutter (23979): #8      initBridge.<anonymous closure>.<anonymous closure> (package:kraken/src/bridge/bridge.dart:40:9)
I/flutter (23979): #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
I/flutter (23979): #10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
I/flutter (23979): #11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:9

```

**Comment by answershuto** [comment]
那个版本有问题，后面修复了

**Comment by colorfulldays** [comment]
> 那个版本有问题，后面修复了
能说下哪次提交修复的吗

**Comment by colorfulldays** [comment]
> 那个版本有问题，后面修复了

这个是基于 jsc 改的 还是 基于quikjs 改的

**Comment by answershuto** [comment]
这个是在 dart 层处理的，跟 JS engine 无关。
