### ISSUE TITLE
kraken-npbt configure 执行报错

### ISSUE THREAD

**Issue by hzbhzb** [openkraken/kraken#966]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.9.0

### 重现步骤 ｜ Steps To Reproduce
在创建的 kraken_plugin 目录下执行 kraken-npbt configure
 
let krakenPath = kraken.rootUri;
                          ^

TypeError: Cannot read properties of undefined (reading 'rootUri')
    at findKraken (/usr/local/lib/node_modules/kraken-npbt/lib/finder.js:10:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/kraken-npbt/bin/kraken-npbt-configure.js:9:20)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by andycall** [comment]
需要在单个插件目录执行，而不是项目根目录。

**Comment by wssgcg1213** [comment]
@hzbhzb 可以按上面 @andycall 说的试一下, 如果还有问题可以回复并 reopen

**Comment by hzbhzb** [comment]
flutter create --template=plugin --ios-language objc --android-language java --platforms ios,android,macos ./my_kraken_plugin

之后在 my_kraken_plugin 这个目录里面执行的上面的指令

**Comment by andycall** [comment]
应该先 flutter pub get 一下

**Comment by hzbhzb** [comment]
有的，已经执行了flutter pub get ,  然后再执行 kraken-npbt configure ，还是报错
Cannot read properties of undefined (reading 'rootUri')
按照你们的这个教程操作的
https://openkraken.com/plugins/plugin/development

**Comment by liuzitong123a** [comment]
遇到同样的问题，并且是在插件的根目录下调用的 kraken-npbt configure
